### PR TITLE
use holochain runner to run full suite

### PR DESCRIPTION
**Pull request by Connoropolous**
this is just the full code of Sprillow/holochain-runner copied in and then modified if a hardcoded way to suit the needs here...

run with ... 
`cd holochain-runner`
`./dry-run.sh` (change name)

### CODE REVIEW

**Comment by pospi** [comment]
This is pretty neat. I'm presuming it works where Tryorama doesn't since it pushes each DNA through the conductor individually rather than the whole app as a single bundle file?

Not sure that I necessarily want to merge an entire other project into here and create a divergent set of code for a temporary measure though. How far off being a standalone lib is `holochain-runner`, and would the startup logic be reducable to `main.rs` alone if the runner was linked as a dependent crate, since `main.rs` is where the app-specific config seems to live?

**Comment by Connoropolous** [comment]
"I'm presuming it works where Tryorama doesn't since it pushes each DNA through the conductor individually rather than the whole app as a single bundle file?"
It goes a little deeper than that. It does install them individually, but here we have the actual direct in-memory reference to the conductor, there are no websockets involved, so we have no size limits for that reason. Even an individual dna could be over 16mb and work.

"Not sure that I necessarily want to merge an entire other project into here and create a divergent set of code for a temporary measure though. "
I pretty much agree with you. 
holochain-runner binaries would work fine, if they it itself were adapted to take an arbitrarily large number of dnas and role_ids, and a membrane proof for each. holochain-runner in our experience has worked great during development and production, and as smooth as or smoother than `hc sandbox` during development. 
However, the whole '6 dnas' thing starts to sound a lot like a `.happ` spec and then we're re-inventing the wheel. 
There's a bit of creative tension between switching to consuming a `.happ` file instead of a `.dna`.

I can potentially bundle up the end binary of this, which was working well for me, instead of including the source code, if you have a concrete need to be able to execute all 6 dnas at once?

**Comment by Connoropolous** [comment]
documentation has been improving here: https://github.com/Sprillow/holochain-runner

**Comment by pospi** [comment]
(TLDR; yes please, I'd love to be able to link to a binary!)

Definitely a concrete need- see [modules in the hREA framework](https://github.com/holo-rea/ecosystem/wiki/Modules-in-the-HoloREA-framework); I count 12 core DNAs, somewhere between 4 and 6 auxillary "dependent" DNAs depending on how we compose the listed features, and 4 other possible specialised companion DNAs. We've also been thinking about DNAs and UIs for higher-order REA based coordination features- such as buyer's clubs, forward planning and resource booking functionality.

But I'm glad to be reading what you're saying about `holochain-runner` and direct access. I think something missed in these conversations so far is that the size of an app bundle doesn't depend just on the number of different *types* of functionality, but on the number of different *instances* of functionality as well. What I mean to say is, "I want to facilitate the capability to deploy an interface connected to 1000s of interconnected Holochain marketplace networks".

**Comment by pospi** [comment]
BTW based on those docs this app shouldn't run, I take it the supported HDK versions have been updated?

**Comment by Connoropolous** [comment]
Oh yeah, I remember being surprised that despite the version discrepancies it all worked. It did actually work I ran it.

**Pull request closed without merging**
